name: Radio Auto Update

on:
  schedule:
    - cron: '0 18 * * *' # 한국 시간 매일 새벽 3시 실행
  workflow_dispatch:

# 🌟 전역 환경 변수를 설정하여 Node.js 24 사용을 강제합니다.
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run Scraper
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: python scraper.py
